#!/usr/bin/env bash
# A Bash script that transfer a file rom client to a sever

# get agrguemnt from command line
PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

scp -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
