#!/usr/bin/env bash
# This script Configure your Nginx server so that /redirect_me is redirecting to another page
# The redirection must be a “301 Moved Permanently”

sudo apt -y update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;" /etc/nginx/sites-available/default
sudo service nginx start
