#!/usr/bin/env bash
# This script display "To infinity and beyond" indefinitely
i=0
trap "I am invincible!!!" SIGTERM

while [ $i -eq 0 ]
do
	echo "To infinity and beyond"
	sleep 2
	trap "I am invicible"
done
