#!/usr/bin/env bash
# This script display number from 1 - 100
# DisplayFizzbuzz when number is multiple of 3 and 5
# Display Fizz when number is multiple of 3
# Display Buzz when number is a multiple of 5
# Otherwise, dispaly the number
i=0
while [ $i -lt 101 ]
do
	if (( i % 3 == 0 && i % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( i % 3 == 0 ))
	then
		echo "Fizz"
	elif (( i % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo $i
	fi
	(( i++ ))
done
