#!/usr/bin/env bash
# This script is displaying "Best School" 10 time
# Print "Hi" at 9th iteration
i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	((i++))
done
