#!/usr/bin/env bash
# This script that display the time for 12 hrs and 59 min
hour=0

while [ "$hour" -le 12 ]
do
	echo "Hour: $hour"
	(( hour ++ ))

	minute=1
	while [ "$minute" -le 59 ]
	do
		echo "$minute"
		(( minute++ ))
	done
done
