#!/usr/bin/env bash
# This script gives you information about a file

file_path="school"
if [ -e "$file_path" ]
then
	echo "school file exists"

	# check if file is empty
	if [ -s "$file_path" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	# check if the file is a regular
	if [ -f "$file_path" ]
	then
		echo "school is regular a file"
	fi

else
	echo "school file does not exist"
fi
